accounts/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    logout_then_login,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.views.generic import TemplateView
from registration.backends.default import views as registration_views

from django.conf import settings
from . import forms


class ActivationView(registration_views.ActivationView):
    def get_success_url(self, user):
        return ('accounts:registration_activation_complete', (), {})


registration_urls = [
    path('register/',
         registration_views.RegistrationView.as_view(success_url=reverse_lazy('accounts:registration_complete')),
         name='registration_register'
         ),
    path('activate/complete/',
         TemplateView.as_view(template_name='registration/activation_complete.html'),
         name='registration_activation_complete'
         ),
    path('activate/resend/',
         registration_views.ResendActivationView.as_view(),
         name='registration_resend_activation'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    path('activate/<activation_key>/',
         ActivationView.as_view(),
         name='registration_activate'),
    path('register/complete/',
         TemplateView.as_view(template_name='registration/registration_complete.html'),
         name='registration_complete'),
    path('register/closed/',
         TemplateView.as_view(template_name='registration/registration_closed.html'),
         name='registration_disallowed'),
]

app_name = 'accounts'
urlpatterns = [
    path('', include(registration_urls)),

    path('login/', LoginView.as_view(authentication_form=forms.MyAuthenticationForm), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('password_change/',
         PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'
         ),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        form_class=forms.MyPasswordResetForm,
        from_email=settings.EMAIL_HOST_USER,
        success_url=reverse_lazy('accounts:password_reset_done'),
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

archives/urls.py
from django.urls import path, re_path, include
from . import views


app_name = 'archives'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list/', views.ArchiveView.as_view(), name='list'),
    path('user/', views.UserView.as_view(), name='user'),
    path('add/', views.CreateArchiveView.as_view(), name='add'),
    path('upload-images/', views.UploadImageView.as_view(), name='upload-images'),

    path('profile/', views.ProfileView.as_view(), name='profile-me'),
    path('profile/<int:uid>/', views.ProfileView.as_view(), name='profile'),
    path('profile/detail/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/order/', views.ProfileOrderView.as_view(), name='profile-order'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/post/', views.ProfilePostView.as_view(), name='profile-post'),

    path('post/<int:pk>/', views.ArchiveDetailView.as_view(), name='detail'),
    path('post/<int:pk>/buy/', views.ArchiveBuyView.as_view(), name='buy'),
    path('post/attach/<int:pk>/', views.AttachmentView.as_view(), name='attachment'),

    path('gift/', views.GiftListView.as_view(), name='shop'),
    path('gift/<int:pk>/', views.GiftDetailView.as_view(), name='gift'),
    path('gift/<int:pk>/buy/', views.OrderCreateView.as_view(), name='order-create'),
    path('gift/order/<int:pk>/', views.OrderDetailView.as_view(), name='order'),

    path('js/', view=views.JavascriptView.as_view(content_type='text/javascript'), name='js'),
]

mooder/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('archives.urls', namespace='archive')),
    path('captcha/', include('captcha.urls')),

    path('management/', include('managements.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/user/edit.html
{% extends 'base.html' %}
{% load template_helper %}

{% block title %}修改用户信息{% endblock %}

{% block body %}
<div class="am-container">
  <div class="am-g">
      <div class="am-u-sm-centered">
          <form class="am-form" id="postform" method="post" enctype="multipart/form-data">
            <div class="am-g">
            <div class="am-u-sm-10">
              <fieldset>
                {% for field in form %}
                        <div class="am-form-group am-form-group-sm">
                        <label>{{ field.label }} &nbsp;
                        <small>
                            {% if field.errors %}
                            <span class="am-text-danger">{{ field.errors | first}}</span>
                            {% else %}
                            {{ field.help_text }}
                            {% endif %}
                        </small></label>
                            {{ field | css:"am-form-field" }}
                        </div>
                {% endfor %}
              </fieldset>
              </div>
              <div class="am-u-sm-2">
                  <h3>{{ request.user.nickname }}</h3>
                <img src="{{ request.user.get_mugshot_url }}" alt="..." class="am-img-thumbnail">
              </div>
            </div>
          {% csrf_token %}
            <div class="am-btn-group am-fr am-margin-right-lg am-margin-top">
              <a href="{% url 'accounts:password_change' %}" class="am-btn am-btn-primary">修改密码</a>
              <button type="button" onclick="history.back(-1)" class="am-btn am-btn-default">返回</button>
              <button type="submit" class="am-btn am-btn-default">提交</button>
            </div>
          </form>
      </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/plupload@2.2.1/js/plupload.full.min.js"></script>
<script type="text/javascript">
window.onload = function () {
    var PluploadHandler = function( $, plupload ) {
        var self = this;
        this.plupload = plupload;
        // Custom example logic
        this.uploader = new plupload.Uploader({
            runtimes : 'html5,flash',
            browse_button : document.getElementById('upbtn'),
            url : "{% url 'archive:upload-images' %}",
            flash_swf_url : "https://cdn.jsdelivr.net/npm/plupload@2.2.1/js/Moxie.swf",
            filters : {
                max_file_size : '5mb',
                mime_types: [
                    {title : "Image files", extensions : "jpg,jpeg,gif,png,bmp"}
                ]
            },
            headers: {
                'X-CSRFToken': $.AMUI.utils.cookie.get('csrftoken')
            },
            init: {
                Error: function(up, err) {
                    console.log("\nError #" + err.code + ": " + err.message);
                }
            }
        });
        this.uploader.init();
        this.uploader.bind("FilesAdded", function (up, files) {
            console.log("+ handlePluploadFilesAdded");
            up.start();
        });
        this.uploader.bind("FileUploaded", function (up, file, res) {
            var f = JSON.parse(res.response);
            if(f.status == 'success') {
                var img = "\n![](" + f.url + ")\n";
                editor.replaceSelection(img)
            }
        });
    };
    var pluploadHandler = new PluploadHandler(jQuery, plupload);
};
</script>
{% endblock %}